- name: Delete storage directory
  ansible.builtin.file:
    path: '{{ wireguard_storage_path }}'
    state: absent
  delegate_to: '{{ wireguard_additional_storage_server }}'
  run_once: true

- name: Ensure storage directory is present
  ansible.builtin.file:
    path: '{{ wireguard_storage_path }}'
    state: directory
    recurse: true
    mode: '700'
  delegate_to: '{{ wireguard_additional_storage_server }}'
  run_once: true


- name: Copy server config to additional storage server
  ansible.builtin.copy:
    src: '{{ wireguard_storage_path }}/{{ wireguard_network_interface }}.conf'
    dest: '{{ wireguard_storage_path }}/{{ wireguard_network_interface }}.conf'
    mode: '700'
  when: not ansible_check_mode
  delegate_to: '{{ wireguard_additional_storage_server }}'
  run_once: true


- name: Ensure clients directory is presents
  ansible.builtin.file:
    path: "{{ wireguard_storage_path }}/clients"
    state: directory
    mode: '700'
  delegate_to: '{{ wireguard_additional_storage_server }}'
  run_once: true


- name: Copy clients configs
  ansible.builtin.copy:
    src: '{{ wireguard_storage_path }}/clients/'
    dest: '{{ wireguard_storage_path }}/clients'
    mode: '700'
  when: not ansible_check_mode
  delegate_to: '{{ wireguard_additional_storage_server }}'
  run_once: true
