- name: Reset server and clients configuration
  ansible.builtin.file:
    path: '{{ wireguard_storage_path }}'
    state: absent
  when: wireguard_reset
  delegate_to: '{{ wireguard_storage_server }}'
  run_once: true


- name: Ensure clients directory is presents on storage server
  ansible.builtin.file:
    path: '{{ wireguard_storage_path }}/clients'
    state: directory
    recurse: true
    mode: '700'
  delegate_to: '{{ wireguard_storage_server }}'
  run_once: true


- name: Define vars wg_new_clients and wg_existing_clients
  ansible.builtin.set_fact:
    wg_new_clients_names: []
    wg_existing_clients_names: []
  when:
    - wg_new_clients_names is not defined or not wg_new_clients_names
    - wg_existing_clients_names is not defined or not wg_existing_clients_names
  delegate_to: '{{ wireguard_storage_server }}'
  run_once: true


- name: 'Check if config already exists : {{ wg_client_name }}'
  ansible.builtin.stat:
    path: '{{ wireguard_storage_path }}/clients/{{ wg_client_name }}.conf'
  register: wg_client_info
  delegate_to: '{{ wireguard_storage_server }}'
  run_once: true


- name: 'Add new client to list : {{ wg_client_name }}'
  ansible.builtin.set_fact:
    wg_new_clients_names: "{{ wg_new_clients_names + [wg_client_name] }}"
  when: not wg_client_info.stat.exists
  delegate_to: '{{ wireguard_storage_server }}'
  run_once: true


- name: 'Add existing client to list : {{ wg_client_name }}'
  ansible.builtin.set_fact:
    wg_existing_clients_names: "{{ wg_existing_clients_names + [wg_client_name] }}"
  when: wg_client_info.stat.exists
  delegate_to: '{{ wireguard_storage_server }}'
  run_once: true
